"""
Contract tests for Contact entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.1.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-05-21 21:59
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_contact_data():
    """Valid create payload for Contact — fields from schema contract."""
    return {
        "first_name": "test_first_name",
        "last_name": "test_last_name",
        "email": "test@example.com",
        "phone": "806-555-1234",
        "company_name": "test_company_name",
        "role": "buyer",
        "notes": "test_notes"
    }

@pytest.fixture
def minimal_contact_data():
    """Minimal create payload — only required fields."""
    return {
        "first_name": "test_first_name",
        "last_name": "test_last_name"
    }



def test_create_contact_contract(client, auth_headers, sample_contact_data):
    """Contract test: POST /contacts/ returns 201 with correct fields."""
    response = client.post("/contacts/", headers=auth_headers, json=sample_contact_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /contacts/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /contacts/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "first_name" in data, "Response missing field: first_name"
    assert "last_name" in data, "Response missing field: last_name"
    assert "email" in data, "Response missing field: email"
    assert "phone" in data, "Response missing field: phone"
    assert "company_name" in data, "Response missing field: company_name"


def test_list_contacts_contract(client, auth_headers):
    """Contract test: GET /contacts/ returns list (not paginated wrapper)."""
    response = client.get("/contacts/", headers=auth_headers)
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("contacts", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_contact_missing_required(client, auth_headers):
    """Contract test: POST /contacts/ with empty body returns 422."""
    response = client.post("/contacts/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /contacts/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"

