"""
Calculator property tests — mathematical invariants.

Auto-generated by JARVIS Dynamic Test Generator v1.1.1 Phase 2.
Verifies that calculator endpoints return mathematically consistent results.
DB-free tests run without county data; DB-dependent tests seed a test county.
Generated: 2026-05-21 21:59
"""

import pytest
from decimal import Decimal


def _d(v) -> Decimal:
    """Coerce to Decimal for precise comparison."""
    if v is None:
        return Decimal("0")
    return Decimal(str(v))


# =========================================================================
# DB-FREE CALCULATOR TESTS (no county required)
# =========================================================================

class TestHoldingCostProperties:
    """POST /calculators/holding-cost mathematical invariants."""

    PAYLOAD = {
        "purchase_price": 200000,
        "loan_rate_pct": 7.0,
        "months_holding": 6,
        "annual_property_tax": 3600,
        "annual_insurance": 1200,
        "monthly_hoa": 150,
        "monthly_maintenance": 100,
    }

    def test_total_equals_monthly_times_months(self, client):
        """total_cost ≈ monthly_cost * months_holding (within rounding tolerance)."""
        resp = client.post("/calculators/holding-cost", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        monthly = _d(data["monthly_cost"])
        total = _d(data["total_cost"])
        expected = monthly * 6
        # Service rounds monthly and total independently from unrounded intermediates,
        # so allow up to $0.10 rounding tolerance per month of holding
        tolerance = Decimal("0.10") * 6
        diff = abs(total - expected)
        assert diff <= tolerance, f"total_cost {total} vs monthly*6 {expected} — diff {diff} exceeds tolerance {tolerance}"

    def test_monthly_cost_positive(self, client):
        """monthly_cost > 0 for non-zero inputs."""
        resp = client.post("/calculators/holding-cost", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        assert _d(data["monthly_cost"]) > 0, "monthly_cost should be positive"

    def test_line_items_present(self, client):
        """Response includes line_items list."""
        resp = client.post("/calculators/holding-cost", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        items = data.get("line_items", [])
        assert isinstance(items, list), "line_items should be a list"
        assert len(items) >= 3, f"Expected >= 3 line items, got {len(items)}"

    def test_zero_months_zero_total(self, client):
        """0 months holding -> total_cost == 0."""
        payload = dict(self.PAYLOAD, months_holding=0)
        resp = client.post("/calculators/holding-cost", json=payload)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        assert _d(data["total_cost"]) == 0, "total_cost should be 0 for 0 months"


class TestBuydownProperties:
    """POST /calculators/buydown mathematical invariants."""

    PAYLOAD = {
        "loan_amount": 300000,
        "base_rate_pct": 7.0,
        "buydown_type": "2-1",
        "points_cost": 5000,
        "loan_term_years": 30,
    }

    def test_net_benefit_identity(self, client):
        """net_benefit == total_savings - points_cost."""
        resp = client.post("/calculators/buydown", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        total = _d(data["total_savings"])
        net = _d(data["net_benefit"])
        cost = Decimal("5000")
        assert net == total - cost, f"net_benefit {net} != total_savings {total} - points_cost {cost}"

    def test_schedule_length(self, client):
        """schedule has loan_term_years entries."""
        resp = client.post("/calculators/buydown", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        schedule = data.get("schedule", [])
        assert len(schedule) == 30, f"Expected 30 years in schedule, got {len(schedule)}"

    def test_year1_rate_reduced(self, client):
        """2-1 buydown: year 1 rate is base - 2."""
        resp = client.post("/calculators/buydown", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        schedule = data.get("schedule", [])
        if not schedule:
            pytest.skip("Empty schedule")
        y1_rate = _d(schedule[0]["rate"])
        assert y1_rate == Decimal("5.00"), f"Year 1 rate {y1_rate} != 5.00 (7.0 - 2.0)"

    def test_year2_rate_reduced(self, client):
        """2-1 buydown: year 2 rate is base - 1."""
        resp = client.post("/calculators/buydown", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        schedule = data.get("schedule", [])
        if len(schedule) < 2:
            pytest.skip("Schedule too short")
        y2_rate = _d(schedule[1]["rate"])
        assert y2_rate == Decimal("6.00"), f"Year 2 rate {y2_rate} != 6.00 (7.0 - 1.0)"

    def test_savings_positive(self, client):
        """Buydown should produce positive savings."""
        resp = client.post("/calculators/buydown", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        assert _d(data["total_savings"]) > 0, "total_savings should be positive for a buydown"


class TestSellVsRentProperties:
    """POST /calculators/sell-vs-rent mathematical invariants."""

    PAYLOAD = {
        "current_value": 300000,
        "monthly_rent_income": 2500,
        "monthly_mortgage_payment": 1800,
        "annual_tax_rate_pct": 2.0,
        "annual_appreciation_rate_pct": 3.0,
        "analysis_years": 5,
    }

    def test_projection_length(self, client):
        """projection has analysis_years entries."""
        resp = client.post("/calculators/sell-vs-rent", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        proj = data.get("projection", [])
        assert len(proj) == 5, f"Expected 5 years, got {len(proj)}"

    def test_years_sequential(self, client):
        """projection years are 1, 2, 3, 4, 5."""
        resp = client.post("/calculators/sell-vs-rent", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        proj = data.get("projection", [])
        for i, entry in enumerate(proj, start=1):
            assert entry["year"] == i, f"Expected year {i}, got {entry.get('year')}"

    def test_recommendation_nonempty(self, client):
        """recommendation_text is a non-empty string."""
        resp = client.post("/calculators/sell-vs-rent", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        rec = data.get("recommendation_text", "")
        assert isinstance(rec, str) and len(rec) > 0, "recommendation_text should be non-empty"

    def test_equity_increases_with_appreciation(self, client):
        """With 3% appreciation, year 5 equity > year 1 equity."""
        resp = client.post("/calculators/sell-vs-rent", json=self.PAYLOAD)
        if resp.status_code != 200:
            pytest.skip(f"Endpoint returned {resp.status_code}")
        data = resp.json()
        proj = data.get("projection", [])
        if len(proj) < 5:
            pytest.skip("Projection too short")
        y1 = _d(proj[0]["equity_if_sell"])
        y5 = _d(proj[4]["equity_if_sell"])
        assert y5 > y1, f"Year 5 equity {y5} should exceed year 1 equity {y1}"


# =========================================================================
# DB-DEPENDENT CALCULATOR TESTS (seed county first)
# =========================================================================

@pytest.fixture
def seed_county(client, auth_headers):
    """Create a test county with known fees for calculator testing.

    Uses minimal decimal fees so math is easy to verify.
    Skips calculator tests if county creation fails.
    """
    payload = {
        "name": "DTG Test County",
        "state": "TX",
        "closing_fee_flat": "500.00",
        "recording_fee_flat": "100.00",
        "transfer_tax_rate_pct": "0.00",
        "survey_fee_flat": "350.00",
        "home_warranty_flat": "450.00",
        "simultaneous_issue_discount_flat": "0.00",
        "is_active": True,
    }
    resp = client.post("/counties/", headers=auth_headers, json=payload)
    if resp.status_code not in (200, 201):
        return None
    return resp.json()


class TestSellerNetSheetProperties:
    """POST /calculators/seller-net-sheet mathematical invariants."""

    def _call(self, client, auth_headers, county_id):
        payload = {
            "sale_price": 250000,
            "existing_loan_balance": 180000,
            "seller_agent_commission_pct": 3.0,
            "buyer_agent_commission_pct": 3.0,
            "county_id": county_id,
            "include_home_warranty": False,
            "include_survey": False,
        }
        return client.post(
            "/calculators/seller-net-sheet", headers=auth_headers, json=payload
        )

    def test_sale_price_echo(self, client, auth_headers, seed_county):
        """Output sale_price matches input."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}: {resp.text[:200]}")
        data = resp.json()
        assert _d(data["sale_price"]) == Decimal("250000"), "sale_price should echo input"

    def test_net_proceeds_identity(self, client, auth_headers, seed_county):
        """net_proceeds == sale_price - loan_payoff - total_closing_costs."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        net = _d(data["net_proceeds"])
        sale = _d(data["sale_price"])
        loan = _d(data["loan_payoff"])
        costs = _d(data["total_closing_costs"])
        expected = sale - loan - costs
        assert net == expected, (
            f"net_proceeds {net} != sale_price {sale} - loan_payoff {loan} "
            f"- total_closing_costs {costs} = {expected}"
        )

    def test_commission_math(self, client, auth_headers, seed_county):
        """total_commission == sale_price * (seller_pct + buyer_pct) / 100."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        commission = _d(data["total_commission"])
        expected = Decimal("250000") * Decimal("6.0") / Decimal("100")
        assert commission == expected, f"total_commission {commission} != {expected}"

    def test_line_items_present(self, client, auth_headers, seed_county):
        """Response includes non-empty line_items list."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        items = data.get("line_items", [])
        assert isinstance(items, list) and len(items) >= 3, (
            f"Expected >= 3 line items, got {len(items)}"
        )


class TestBuyerEstimateProperties:
    """POST /calculators/buyer-estimate mathematical invariants."""

    def _call(self, client, auth_headers, county_id):
        payload = {
            "purchase_price": 250000,
            "loan_amount": 200000,
            "loan_type": "conventional",
            "interest_rate": 7.0,
            "county_id": county_id,
            "annual_property_taxes": 3600,
            "annual_homeowners_insurance": 1200,
        }
        return client.post(
            "/calculators/buyer-estimate", headers=auth_headers, json=payload
        )

    def test_down_payment_identity(self, client, auth_headers, seed_county):
        """down_payment == purchase_price - loan_amount."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}: {resp.text[:200]}")
        data = resp.json()
        dp = _d(data["down_payment"])
        expected = Decimal("250000") - Decimal("200000")
        assert dp == expected, f"down_payment {dp} != {expected}"

    def test_purchase_price_echo(self, client, auth_headers, seed_county):
        """Output purchase_price matches input."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        assert _d(data["purchase_price"]) == Decimal("250000"), "purchase_price should echo input"

    def test_loan_amount_echo(self, client, auth_headers, seed_county):
        """Output loan_amount matches input."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        assert _d(data["loan_amount"]) == Decimal("200000"), "loan_amount should echo input"

    def test_line_items_present(self, client, auth_headers, seed_county):
        """Response includes non-empty line_items list."""
        if seed_county is None:
            pytest.skip("County seed failed")
        resp = self._call(client, auth_headers, seed_county["id"])
        if resp.status_code != 200:
            pytest.skip(f"Calculator returned {resp.status_code}")
        data = resp.json()
        items = data.get("line_items", [])
        assert isinstance(items, list) and len(items) >= 3, (
            f"Expected >= 3 line items, got {len(items)}"
        )
