"""
Contract tests for ReissueDiscount entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.1.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-05-21 21:59
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_reissue_discount_data():
    """Valid create payload for ReissueDiscount — fields from schema contract."""
    return {
        "name": "test_name",
        "discount_percentage": 10.0,
        "min_years": "test_min_years",
        "max_years": "test_max_years",
        "is_active": True
    }

@pytest.fixture
def minimal_reissue_discount_data():
    """Minimal create payload — only required fields."""
    return {
        "name": "test_name",
        "discount_percentage": 10.0,
        "min_years": "test_min_years",
        "max_years": "test_max_years",
        "is_active": True
    }



def test_create_reissue_discount_contract(client, auth_headers, sample_reissue_discount_data):
    """Contract test: POST /reissue_discounts/ returns 201 with correct fields."""
    response = client.post("/reissue_discounts/", headers=auth_headers, json=sample_reissue_discount_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /reissue_discounts/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /reissue_discounts/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "name" in data, "Response missing field: name"
    assert "discount_percentage" in data, "Response missing field: discount_percentage"
    assert "min_years" in data, "Response missing field: min_years"
    assert "max_years" in data, "Response missing field: max_years"
    assert "is_active" in data, "Response missing field: is_active"


def test_list_reissue_discounts_contract(client, auth_headers):
    """Contract test: GET /reissue_discounts/ returns list (not paginated wrapper)."""
    response = client.get("/reissue_discounts/", headers=auth_headers)
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("reissue_discounts", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"

