"""
Contract tests for RateBracket entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.1.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-05-21 21:59
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_rate_bracket_data():
    """Valid create payload for RateBracket — fields from schema contract."""
    return {
        "rate_table_id": 5.50,
        "min_value": "test_min_value",
        "max_value": "test_max_value",
        "rate_per_thousand": 5.50
    }

@pytest.fixture
def minimal_rate_bracket_data():
    """Minimal create payload — only required fields."""
    return {
        "rate_table_id": 5.50,
        "min_value": "test_min_value",
        "max_value": "test_max_value",
        "rate_per_thousand": 5.50
    }



def test_create_rate_bracket_contract(client, auth_headers, sample_rate_bracket_data):
    """Contract test: POST /rate_brackets/ returns 201 with correct fields."""
    response = client.post("/rate_brackets/", headers=auth_headers, json=sample_rate_bracket_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /rate_brackets/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /rate_brackets/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "rate_table_id" in data, "Response missing field: rate_table_id"
    assert "min_value" in data, "Response missing field: min_value"
    assert "max_value" in data, "Response missing field: max_value"
    assert "rate_per_thousand" in data, "Response missing field: rate_per_thousand"
    assert "created_at" in data, "Response missing field: created_at"


def test_list_rate_brackets_contract(client, auth_headers):
    """Contract test: GET /rate_brackets/ returns list (not paginated wrapper)."""
    response = client.get("/rate_brackets/", headers=auth_headers)
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("rate_brackets", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"

