"""
Contract tests for Notification entity.

Auto-generated by JARVIS Dynamic Test Generator v1.1.1.
Tests use EXACT field names from schema contracts — no hallucinated fields.
Generated: 2026-05-21 21:59
"""

import pytest
from fastapi.testclient import TestClient


@pytest.fixture
def sample_notification_data():
    """Valid create payload for Notification — fields from schema contract."""
    return {
        "title": "test_title",
        "description": "test_description",
        "status": "unread"
    }

@pytest.fixture
def minimal_notification_data():
    """Minimal create payload — only required fields."""
    return {
        "title": "test_title"
    }



def test_create_notification_contract(client, auth_headers, sample_notification_data):
    """Contract test: POST /notifications/ returns 201 with correct fields."""
    response = client.post("/notifications/", headers=auth_headers, json=sample_notification_data)
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /notifications/ (status {response.status_code}) — singleton resource")
    if response.status_code not in (201, 200):
        pytest.skip(f"POST /notifications/ returned {response.status_code} — payload may need seeded dependencies")
    data = response.json()
    assert "id" in data, "Response missing field: id"
    assert "title" in data, "Response missing field: title"
    assert "description" in data, "Response missing field: description"
    assert "status" in data, "Response missing field: status"
    assert "created_at" in data, "Response missing field: created_at"


def test_list_notifications_contract(client, auth_headers):
    """Contract test: GET /notifications/ returns list (not paginated wrapper)."""
    response = client.get("/notifications/", headers=auth_headers)
    assert response.status_code == 200
    data = response.json()
    # Handle both flat list and paginated wrapper
    items = data if isinstance(data, list) else data.get("items", data.get("notifications", []))
    assert isinstance(items, list), f"Expected list, got {type(items)}"


def test_create_notification_missing_required(client, auth_headers):
    """Contract test: POST /notifications/ with empty body returns 422."""
    response = client.post("/notifications/", headers=auth_headers, json={})
    if response.status_code in (405, 404):
        pytest.skip(f"POST not supported on /notifications/ (status {response.status_code}) — singleton resource")
    assert response.status_code == 422, f"Expected 422 for empty payload, got {response.status_code}"


def test_notification_no_content_field(client, auth_headers, sample_notification_data):
    """Contract test: response uses 'description' not 'content'."""
    response = client.post("/notifications/", headers=auth_headers, json=sample_notification_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "content" not in data, "Response should use 'description' not 'content'"
        assert "description" in data, "Response missing 'description' field"


def test_notification_no_body_field(client, auth_headers, sample_notification_data):
    """Contract test: response uses 'description' not 'body'."""
    response = client.post("/notifications/", headers=auth_headers, json=sample_notification_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "body" not in data, "Response should use 'description' not 'body'"
        assert "description" in data, "Response missing 'description' field"


def test_notification_no_message_field(client, auth_headers, sample_notification_data):
    """Contract test: response uses 'description' not 'message'."""
    response = client.post("/notifications/", headers=auth_headers, json=sample_notification_data)
    if response.status_code in (200, 201):
        data = response.json()
        assert "message" not in data, "Response should use 'description' not 'message'"
        assert "description" in data, "Response missing 'description' field"

