"""
routes/countys.py  v1.0.0
Generated by JARVIS RouteSkeletonGenerator.
CRUD routes for County entity.
"""
from __future__ import annotations
import logging
from typing import List

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from database import get_db
from schemas.county import CountyCreate, CountyResponse, CountyUpdate
from services.county_service import CountyService

logger = logging.getLogger(__name__)

router = APIRouter(tags=["counties"])


def get_svc(db: Session = Depends(get_db)) -> CountyService:
    return CountyService()


@router.get("/", response_model=List[CountyResponse])
def list_counties(
    skip: int = 0,
    limit: int = 100,
    db: Session = Depends(get_db),
):
    """List all counties with pagination."""
    svc = CountyService()
    return svc.list_counties(skip=skip, limit=limit, db=db)


@router.get("/{county_id}", response_model=CountyResponse)
def get_county(county_id: int, db: Session = Depends(get_db)):
    """Get a county by ID."""
    svc = CountyService()
    county = svc.get_county_by_id(county_id, db=db)
    if not county:
        raise HTTPException(status_code=404, detail="County not found")
    return county


@router.post("/", response_model=CountyResponse, status_code=201)
def create_county(data: CountyCreate, db: Session = Depends(get_db)):
    """Create a new county."""
    svc = CountyService()
    return svc.create_county(data, db=db)


@router.put("/{county_id}", response_model=CountyResponse)
def update_county(
    county_id: int,
    data: CountyUpdate,
    db: Session = Depends(get_db),
):
    """Update an existing county."""
    svc = CountyService()
    county = svc.update_county(county_id, data, db=db)
    if not county:
        raise HTTPException(status_code=404, detail="County not found")
    return county


@router.delete("/{county_id}", status_code=200)
def delete_county(county_id: int, db: Session = Depends(get_db)):
    """Delete a county by ID."""
    svc = CountyService()
    deleted = svc.delete_county(county_id, db=db)
    if not deleted:
        raise HTTPException(status_code=404, detail="County not found")
    return True

countys_router = router  # FIX-ROUTER-ALIAS